[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false


# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Threshold for audio recording
    min_decibels = -45
    # Delay for the user to start speaking in MS
    initial_silence_timeout = 3000
    # Delay for the user to continue speaking in MS. If the user stops speaking for this duration, the recording will stop.
    silence_timeout = 1500
    # Above this duration (MS), the recording will forcefully stop.
    max_duration = 15000
    # Duration of the audio chunks in MS
    chunk_duration = 1000
    # Sample rate of the audio
    sample_rate = 44100

[UI]
# Name of the assistant.
name = "Bitcoin Mempool AI Assistant"

# Description of the assistant. This is used for HTML tags.
description = "Your go-to assistant for all things Bitcoin and blockchain!"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/bigsk1/btc-mempool-ai"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/test.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom meta image url.
custom_meta_image_url = "https://imagedelivery.net/WfhVb8dSNAAvdXUdMfBuPQ/578ff544-27ed-456a-82bc-9c0b22a3d800/public"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

[UI.theme]
    default = "dark"

# Override default MUI light theme.
[UI.theme.light]
    background = "#FFFFFF"
    paper = "#F8F8F8"
    [UI.theme.light.primary]
        main = "#F7931A"  # Bitcoin orange
        dark = "#E87D16"
        light = "#FAB463"
    [UI.theme.light.text]
        primary = "#212121"
        secondary = "#4A4A4A"

# Override default MUI dark theme.
[UI.theme.dark]
    background = "#1E1E1E"
    paper = "#2D2D2D"
    [UI.theme.dark.primary]
        main = "#F7931A"  # Bitcoin orange
        dark = "#E87D16"
        light = "#FAB463"
    [UI.theme.dark.text]
        primary = "#FFFFFF"
        secondary = "#BDBDBD"

[meta]
generated_by = "1.1.305"

